### ISSUE TITLE
Do you plan to create a GitHub Action?

### ISSUE THREAD

**Issue by geoperez** [andrewlock/auto-assign-issues#2]
Hi, I'm interested to know if you are going to port your app to a GitHub Action.

Thanks!

**Comment by andrewlock** [comment]
Wasn't intending on it, but might be interesting! Is there any practical benefit do you know?

**Comment by geoperez** [comment]
Mostly that you don't need to deploy the app:

https://help.github.com/en/github/automating-your-workflow-with-github-actions/about-actions#comparing-github-actions-to-github-apps
